version: '3'
services:
  hsm-sim-tcpserver:
    image: 'hsm-sim-tcpserver'
    ports:
      - "1500:1500"
    restart: always
    networks:
      - hsm-sim-parent_default

networks:
  hsm-sim-parent_default:
    external: true
